name: redirect
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  fluttertoast: ^8.2.5
  flutter_contacts: ^1.1.9+2
  shimmer: ^3.0.0
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  video_thumbnail: ^0.5.3
  share_plus: ^10.0.0
  image_gallery_saver: ^2.0.3
  cr_file_saver: ^0.0.2+1
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100


